/*
 * This Java source file was generated by the Gradle 'init' task.
 */package atelier11;

import com.google.common.base.MoreObjects.ToStringHelper;

//initialise la classe shape
public class Shape{

    // initialise les variables et les met proteger
   protected String isColor;
   protected boolean isFilled;

   //constructeur qui set les variables
     public Shape(String isColor, Boolean isFilled) {
       isColor = "vert";
       isFilled = true;
    }

    //constructeur qui initialise le constructeur
    public Shape() { }

    //encapsule le code
    public void getColor() {
    }
    public void setColor(String newColor) {
        this.isColor = newColor;
    }
    public void getFilled() {
    }
    public void setFilled(Boolean newFilled) {
        this.isFilled = newFilled;
    }

    public String toString() {
        return "the shape color is " + this.isColor + "and filled is " + isFilled;
    }

    public static void main(String[] args) {
    }
}